[build]
  command = "next build"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ğŸ‘‡ ceci force Netlify Ã  scanner les forms dans le dossier .next/server/app
[[plugins.inputs]]
  # nÃ©cessaire pour dÃ©tecter les formulaires de lâ€™App Router
  includeAppRouterPages = true
